version: 0.2

phases:
  install:
    commands:
      - echo Entering install phase...
      - wget https://jcenter.bintray.com/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.tar.gz 
      - tar xzvf apache-maven-3.3.9-bin.tar.gz -C /opt/
      - export PATH=/opt/apache-maven-3.3.9/bin:$PATH
 
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn install
      
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`i

artifacts:
  type: zip
  files:
    - 'appspec.yml'
    - 'target/0.0.1-SNAPSHOT.diusingboot.jar'