version: 0.2

phases:
  install:
    commands:
      - echo Entering install phase...
      - .\script\dotnetpackage.ps1
  build:
    commands:
      - echo Entering build phase...
      - msbuild

      
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`i

artifacts:
  type: zip
  files:
    - diusingboot/appspec.yml

