version: 0.2

phases:
  install:
    commands:
      - echo Entering install phase...
      - New-Item -Type Directory $Env:ProgramFiles\NuGet; 
      - Invoke-WebRequest -UseBasicParsing https://dist.nuget.org/win-x86-commandline/v4.4.1/nuget.exe -OutFile $Env:ProgramFiles\NuGet\nuget.exe
      - Invoke-WebRequest -UseBasicParsing https://download.visualstudio.microsoft.com/download/pr/12210059/e64d79b40219aea618ce2fe10ebd5f0d/vs_BuildTools.exe -OutFile vs_BuildTools.exe;
      - Start-Process vs_BuildTools.exe -ArgumentList '--add', 'Microsoft.VisualStudio.Workload.MSBuildTools', '--add', 'Microsoft.VisualStudio.Workload.NetCoreBuildTools', '--add', 'Microsoft.VisualStudio.Workload.WebBuildTools;includeRecommended', '--quiet', '--norestart', '--nocache' -NoNewWindow -Wait;
      - Start-Process -Wait -FilePath $Env:ProgramFiles\NuGet\nuget.exe -Argument "/silent" -PassThru
      - setx /M PATH "${Env:ProgramFiles}\NuGet\;${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      - ('4.0', '4.5.2', '4.6.2', '4.7.2') `| %{ `Invoke-WebRequest -UseBasicParsing https://dotnetbinaries.blob.core.windows.net/referenceassemblies/v${_}.zip -OutFile referenceassemblies.zip; `Expand-Archive -Force referenceassemblies.zip -DestinationPath "${Env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework\.NETFramework\"; `Remove-Item -Force referenceassemblies.zip; `}
 
  build:
    commands:
      - echo Entering build phase...
      - msbuild

      
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`i

artifacts:
  type: zip
  files:
    - diusingboot/appspec.yml

